import * as React from "react";
const SVGComponent = (props) => (
  <svg
    id="Layer_1"
    data-name="Layer 1"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 420 560"
    {...props}
  >
    <defs>
      <style>
        {
          "\n      .cls-1 {\n        fill: #fff;\n        stroke: #000;\n        stroke-miterlimit: 10;\n        stroke-width: .25px;\n      }\n\n      .cls-2 {\n        fill: none;\n      }\n\n      .cls-3 {\n        fill: #848789;\n      }\n    "
        }
      </style>
    </defs>
    <rect
      id="background"
      className="cls-2"
      x={0.5}
      y={-0.5}
      width={419}
      height={560}
    />
    <g id="trunk">
      <circle
        id="trunk-2"
        data-name="trunk"
        className="cls-1"
        cx={33.39}
        cy={282.41}
        r={20}
      />
      <circle id="techDents" className="cls-1" cx={66.59} cy={266.41} r={15} />
      <circle id="aluminium" className="cls-3" cx={66.59} cy={298.41} r={15} />
    </g>
    <g id="roof">
      <circle
        id="roof-2"
        data-name="roof"
        className="cls-1"
        cx={203.13}
        cy={282.41}
        r={20}
      />
      <circle
        id="techDents-2"
        data-name="techDents"
        className="cls-1"
        cx={236.33}
        cy={266.41}
        r={15}
      />
      <circle
        id="aluminium-2"
        data-name="aluminium"
        className="cls-3"
        cx={236.33}
        cy={298.41}
        r={15}
      />
    </g>
    <g id="hood">
      <circle
        id="hood-2"
        data-name="hood"
        className="cls-1"
        cx={368.88}
        cy={282.41}
        r={20}
      />
      <circle
        id="techDents-3"
        data-name="techDents"
        className="cls-1"
        cx={402.08}
        cy={266.41}
        r={15}
      />
      <circle
        id="aluminium-3"
        data-name="aluminium"
        className="cls-3"
        cx={402.08}
        cy={298.41}
        r={15}
      />
    </g>
    <g id="cowl">
      <circle
        id="cowl-2"
        data-name="cowl"
        className="cls-1"
        cx={296.01}
        cy={282.41}
        r={20}
      />
      <circle
        id="techDents-4"
        data-name="techDents"
        className="cls-1"
        cx={329.21}
        cy={266.41}
        r={15}
      />
      <circle
        id="aluminium-4"
        data-name="aluminium"
        className="cls-3"
        cx={329.21}
        cy={298.41}
        r={15}
      />
    </g>
    <g id="rightFrontFender">
      <circle
        id="rightFrontFender-2"
        data-name="rightFrontFender"
        className="cls-1"
        cx={336}
        cy={455.5}
        r={20}
      />
      <circle
        id="techDents-5"
        data-name="techDents"
        className="cls-1"
        cx={369.2}
        cy={439.5}
        r={15}
      />
      <circle
        id="aluminium-5"
        data-name="aluminium"
        className="cls-3"
        cx={369.2}
        cy={471.5}
        r={15}
      />
    </g>
    <g id="rightFrontDoor">
      <circle
        id="rightFrontDoor-2"
        data-name="rightFrontDoor"
        className="cls-1"
        cx={252.51}
        cy={450.5}
        r={20}
      />
      <circle
        id="techDents-6"
        data-name="techDents"
        className="cls-1"
        cx={285.7}
        cy={434.5}
        r={15}
      />
      <circle
        id="aluminium-6"
        data-name="aluminium"
        className="cls-3"
        cx={285.7}
        cy={466.5}
        r={15}
      />
    </g>
    <g id="rightRocker">
      <circle
        id="rightRocker-2"
        data-name="rightRocker"
        className="cls-1"
        cx={205.26}
        cy={503.5}
        r={20}
      />
      <circle
        id="techDents-7"
        data-name="techDents"
        className="cls-1"
        cx={238.46}
        cy={487.5}
        r={15}
      />
      <circle
        id="aluminium-7"
        data-name="aluminium"
        className="cls-3"
        cx={238.46}
        cy={519.5}
        r={15}
      />
    </g>
    <g id="rightRearDoor">
      <circle
        id="rightRearDoor-2"
        data-name="rightRearDoor"
        className="cls-1"
        cx={164.01}
        cy={450.5}
        r={20}
      />
      <circle
        id="techDents-8"
        data-name="techDents"
        className="cls-1"
        cx={197.21}
        cy={434.5}
        r={15}
      />
      <circle
        id="aluminium-8"
        data-name="aluminium"
        className="cls-3"
        cx={197.21}
        cy={466.5}
        r={15}
      />
    </g>
    <g id="rightRearQuarter">
      <circle
        id="rightRearQuarter-2"
        data-name="rightRearQuarter"
        className="cls-1"
        cx={70.51}
        cy={445.5}
        r={20}
      />
      <circle
        id="techDents-9"
        data-name="techDents"
        className="cls-1"
        cx={103.71}
        cy={429.5}
        r={15}
      />
      <circle
        id="aluminium-9"
        data-name="aluminium"
        className="cls-3"
        cx={103.71}
        cy={461.5}
        r={15}
      />
    </g>
    <g id="leftFrontFender">
      <circle
        id="leftFrontFender-2"
        data-name="leftFrontFender"
        className="cls-1"
        cx={336}
        cy={99.09}
        r={20}
      />
      <circle
        id="techDents-10"
        data-name="techDents"
        className="cls-1"
        cx={369.2}
        cy={83.09}
        r={15}
      />
      <circle
        id="aluminium-10"
        data-name="aluminium"
        className="cls-3"
        cx={369.2}
        cy={115.09}
        r={15}
      />
    </g>
    <g id="leftFrontDoor">
      <circle
        id="leftFrontDoor-2"
        data-name="leftFrontDoor"
        className="cls-1"
        cx={249.51}
        cy={109.09}
        r={20}
      />
      <circle
        id="techDents-11"
        data-name="techDents"
        className="cls-1"
        cx={282.7}
        cy={93.09}
        r={15}
      />
      <circle
        id="aluminium-11"
        data-name="aluminium"
        className="cls-3"
        cx={282.7}
        cy={125.09}
        r={15}
      />
    </g>
    <g id="leftRocker">
      <circle
        id="leftRocker-2"
        data-name="leftRocker"
        className="cls-1"
        cx={206.26}
        cy={53.72}
        r={20}
      />
      <circle
        id="techDents-12"
        data-name="techDents"
        className="cls-1"
        cx={239.46}
        cy={37.72}
        r={15}
      />
      <circle
        id="aluminium-12"
        data-name="aluminium"
        className="cls-3"
        cx={239.46}
        cy={69.72}
        r={15}
      />
    </g>
    <g id="leftRearQuarter">
      <circle
        id="leftRearQuarter-2"
        data-name="leftRearQuarter"
        className="cls-1"
        cx={70.51}
        cy={109.09}
        r={20}
      />
      <circle
        id="techDents-13"
        data-name="techDents"
        className="cls-1"
        cx={103.71}
        cy={93.09}
        r={15}
      />
      <circle
        id="aluminium-13"
        data-name="aluminium"
        className="cls-3"
        cx={103.71}
        cy={125.09}
        r={15}
      />
    </g>
    <g id="rightRail">
      <circle
        id="rightRail-2"
        data-name="rightRail"
        className="cls-1"
        cx={140.88}
        cy={336.6}
        r={20}
      />
      <circle
        id="techDents-14"
        data-name="techDents"
        className="cls-1"
        cx={174.08}
        cy={320.6}
        r={15}
      />
      <circle
        id="aluminium-14"
        data-name="aluminium"
        className="cls-3"
        cx={174.08}
        cy={352.6}
        r={15}
      />
    </g>
    <g id="leftRail">
      <circle
        id="leftRail-2"
        data-name="leftRail"
        className="cls-1"
        cx={130.88}
        cy={229.35}
        r={20}
      />
      <circle
        id="techDents-15"
        data-name="techDents"
        className="cls-1"
        cx={164.08}
        cy={213.35}
        r={15}
      />
      <circle
        id="aluminium-15"
        data-name="aluminium"
        className="cls-3"
        cx={164.08}
        cy={245.35}
        r={15}
      />
    </g>
  </svg>
);
export default SVGComponent;
